Added windows pytest
SupertechLabs/applications-superstaq pull request #58
Opened 2022-05-12 16:29 UTC by PalashGoiporia

2022-05-12 16:29 UTC, vtomole commented
Please solve the conflict.

2022-05-12 20:24 UTC, PalashGoiporia commented
@vtomole not sure how to deal with the permission error. It passes locally.

2022-05-12 20:32 UTC, vtomole commented
@PalashGoiporia  You need to run the formatter.

2022-05-12 20:33 UTC, vtomole commented
Won't merge until @richrines1 approves.

2022-05-12 21:54 UTC, PalashGoiporia commented
Ready for review @vtomole @richrines1

2022-05-12 22:01 UTC, vtomole requested changes

2022-05-12 22:01 UTC, vtomole commented on applications_superstaq/user_config_test.py
> +    pulse = tempfile.NamedTemporaryFile("w+", delete=False)
Revert from `w+` to `w`

2022-05-12 22:01 UTC, vtomole commented on applications_superstaq/user_config_test.py
> +    variable = tempfile.NamedTemporaryFile("w+", delete=False)
Revert from `w+` to `w`

2022-05-12 22:01 UTC, vtomole commented on applications_superstaq/user_config_test.py
> +    variables_file = tempfile.NamedTemporaryFile("w+", delete=False)
Revert from `w+` to `w`

2022-05-12 22:19 UTC, PalashGoiporia commented on applications_superstaq/user_config_test.py
> +    pulses_file = tempfile.NamedTemporaryFile("w+", delete=False)
I think this one is needed

2022-05-12 22:19 UTC, PalashGoiporia commented on applications_superstaq/user_config_test.py
> +    variables_file = tempfile.NamedTemporaryFile("w+", delete=False)
I think this one is needed

2022-05-13 20:56 UTC, vtomole commented on applications_superstaq/user_config_test.py
> +        variables_file.write("Hello")
Revert variables to write `World`.

2022-05-16 18:14 UTC, vtomole approved these changes

2022-05-16 18:14 UTC, merged

2022-07-08 03:00 UTC, singular-value commented
![billgates](https://user-images.githubusercontent.com/3976048/177908495-50979258-989b-4ee1-bf8b-d72673a7d79e.gif)